"""initial migrations

Revision ID: 43d4ab01c380
Revises: 
Create Date: 2024-10-06 02:25:13.813527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d4ab01c380'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('open_price', sa.String(), nullable=True),
    sa.Column('close_price', sa.String(), nullable=True),
    sa.Column('high_price', sa.String(), nullable=True),
    sa.Column('low_price', sa.String(), nullable=True),
    sa.Column('volume', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('file_metadata_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_metadata_id'], ['file_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_close_price'), 'security', ['close_price'], unique=False)
    op.create_index(op.f('ix_security_date'), 'security', ['date'], unique=False)
    op.create_index(op.f('ix_security_high_price'), 'security', ['high_price'], unique=False)
    op.create_index(op.f('ix_security_low_price'), 'security', ['low_price'], unique=False)
    op.create_index(op.f('ix_security_name'), 'security', ['name'], unique=False)
    op.create_index(op.f('ix_security_open_price'), 'security', ['open_price'], unique=False)
    op.create_index(op.f('ix_security_volume'), 'security', ['volume'], unique=False)
    op.add_column('file_metadata', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('file_metadata', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_metadata', 'updated_at')
    op.drop_column('file_metadata', 'created_at')
    op.drop_index(op.f('ix_security_volume'), table_name='security')
    op.drop_index(op.f('ix_security_open_price'), table_name='security')
    op.drop_index(op.f('ix_security_name'), table_name='security')
    op.drop_index(op.f('ix_security_low_price'), table_name='security')
    op.drop_index(op.f('ix_security_high_price'), table_name='security')
    op.drop_index(op.f('ix_security_date'), table_name='security')
    op.drop_index(op.f('ix_security_close_price'), table_name='security')
    op.drop_table('security')
    # ### end Alembic commands ###
