"""generated tables

Revision ID: 9c78c22cdd1b
Revises:
Create Date: 2025-02-01 19:31:04.168985

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c78c22cdd1b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_metadata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("file_name", sa.String(), nullable=True),
        sa.Column("file_path", sa.String(), nullable=True),
        sa.Column("file_size", sa.String(), nullable=True),
        sa.Column("file_type", sa.String(), nullable=True),
        sa.Column("upload_date", sa.Date(), nullable=True),
        sa.Column("is_valid", sa.Boolean(), nullable=True),
        sa.Column("validation_message", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "security",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("Name", sa.String(), nullable=True),
        sa.Column("Open", sa.String(), nullable=True),
        sa.Column("Close", sa.String(), nullable=True),
        sa.Column("High", sa.String(), nullable=True),
        sa.Column("Low", sa.String(), nullable=True),
        sa.Column("Volume", sa.String(), nullable=True),
        sa.Column("Date", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("file_metadata_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_metadata_id"], ["file_metadata.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_security_Close"), "security", ["Close"], unique=False)
    op.create_index(op.f("ix_security_Date"), "security", ["Date"], unique=False)
    op.create_index(op.f("ix_security_High"), "security", ["High"], unique=False)
    op.create_index(op.f("ix_security_Low"), "security", ["Low"], unique=False)
    op.create_index(op.f("ix_security_Name"), "security", ["Name"], unique=False)
    op.create_index(op.f("ix_security_Open"), "security", ["Open"], unique=False)
    op.create_index(op.f("ix_security_Volume"), "security", ["Volume"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_security_Volume"), table_name="security")
    op.drop_index(op.f("ix_security_Open"), table_name="security")
    op.drop_index(op.f("ix_security_Name"), table_name="security")
    op.drop_index(op.f("ix_security_Low"), table_name="security")
    op.drop_index(op.f("ix_security_High"), table_name="security")
    op.drop_index(op.f("ix_security_Date"), table_name="security")
    op.drop_index(op.f("ix_security_Close"), table_name="security")
    op.drop_table("security")
    op.drop_table("file_metadata")
    # ### end Alembic commands ###
